```
Preprocessing in Machine Learning is the process of cleaning and transforming raw data into a format that a machine learning model can use effectively.

Why is preprocessing important?

Raw data often contains:

Missing values
Duplicate records
Incorrect or inconsistent data
Categorical (text) values
Features with different scales
Noise and outliers

Preprocessing improves data quality, which can lead to better model performance.

```

In [12]:
import numpy as np 

import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv(r"C:\Users\Saloni\Downloads\netflix_titles.csv\netflix_title.csv.csv")

In [4]:
df.shape

(8807, 12)

In [5]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [6]:
df.tail()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [11]:
%pip install scikit-learn
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

Defaulting to user installation because normal site-packages is not writeable
Collecting scikit-learn
  Downloading scikit_learn-1.9.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\Saloni\AppData\Roaming\Python\Python314\site-packages (from scikit-learn) (2.5.1)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.18.0-cp314-cp314-win_amd64.whl.metadata (61 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Downloading narwhals-2.24.0-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.9.0-cp314-cp314-win_amd64.whl (8.3 MB)
   ---------------------------------------- 0.0/8.3 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.3 MB 3.8 MB/s eta 0:00:03
   ------ --------------------------------- 1.3/8.3 MB 4.0 MB/s eta 0:00:02
   ----------- ---------------------------- 2.4/8.3 MB 4.2 MB/s eta 0:00:02
   --------------- ------------------------ 3.1/8.3 MB 4.2 MB/s eta 0:00:02
   -------------------- ------------------- 4.2/8.3 MB 4.3 MB/s eta 0:00:01
   --------------------- ------------------ 4.5/8.3 MB 4.0 MB/s eta 0:00:01
   ------------------------- -------------- 5.2/8.3 MB 3.8 MB/s eta 0:00:01
   ----------------------------- ---------- 6.0/8.3 MB 3.8 MB/s eta 0:00:01
   ------------------------------- -------- 6.6/8.3 MB 3.7 MB/s eta 0:00:01
   ----------------------------------- ---- 7.3/8.3 MB 3.6 MB/s eta 0:00:01
   ------------------------------------- -- 7.9/8.3 MB 3.6 MB/s eta 0:00:01
   ---------------------------------------- 8.3/8.3 MB 3.5 MB/s  0:00:02
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading narwhals-2.24.0-py3-none-any.whl (461 kB)
Downloading scipy-1.18.0-cp314-cp314-win_amd64.whl (37.3 MB)
   ---------------------------------------- 0.0/37.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/37.3 MB ? eta -:--:--
    --------------------------------------- 0.8/37.3 MB 2.6 MB/s eta 0:00:14
   - -------------------------------------- 1.3/37.3 MB 2.3 MB/s eta 0:00:16
   - -------------------------------------- 1.8/37.3 MB 2.2 MB/s eta 0:00:16
   -- ------------------------------------- 2.1/37.3 MB 2.2 MB/s eta 0:00:17
   -- ------------------------------------- 2.6/37.3 MB 2.2 MB/s eta 0:00:16
   --- ------------------------------------ 3.1/37.3 MB 2.1 MB/s eta 0:00:16
   --- ------------------------------------ 3.4/37.3 MB 2.0 MB/s eta 0:00:17
   --- ------------------------------------ 3.7/37.3 MB 2.0 MB/s eta 0:00:17
   ---- ----------------------------------- 3.9/37.3 MB 2.0 MB/s eta 0:00:17
   ---- ----------------------------------- 4.5/37.3 MB 1.9 MB/s eta 0:00:17
   ----- ---------------------------------- 4.7/37.3 MB 1.9 MB/s eta 0:00:17
   ----- ---------------------------------- 5.0/37.3 MB 1.9 MB/s eta 0:00:18
   ----- ---------------------------------- 5.5/37.3 MB 1.9 MB/s eta 0:00:17
   ------ --------------------------------- 5.8/37.3 MB 1.9 MB/s eta 0:00:17
   ------ --------------------------------- 6.0/37.3 MB 1.9 MB/s eta 0:00:17
   ------ --------------------------------- 6.3/37.3 MB 1.9 MB/s eta 0:00:17
   ------- -------------------------------- 6.6/37.3 MB 1.8 MB/s eta 0:00:18
   ------- -------------------------------- 6.8/37.3 MB 1.8 MB/s eta 0:00:18
   ------- -------------------------------- 7.1/37.3 MB 1.8 MB/s eta 0:00:18
   -------- ------------------------------- 7.6/37.3 MB 1.7 MB/s eta 0:00:18
   -------- ------------------------------- 7.9/37.3 MB 1.7 MB/s eta 0:00:17
   -------- ------------------------------- 8.1/37.3 MB 1.7 MB/s eta 0:00:17
   -------- ------------------------------- 8.4/37.3 MB 1.7 MB/s eta 0:00:17
   --------- ------------------------------ 8.9/37.3 MB 1.7 MB/s eta 0:00:17
   --------- ------------------------------ 9.2/37.3 MB 1.7 MB/s eta 0:00:17
   ---------- ----------------------------- 9.4/37.3 MB 1.7 MB/s eta 0:00:17
   ---------- ----------------------------- 10.0/37.3 MB 1.7 MB/s eta 0:00:16
   ----------- ---------------------------- 10.5/37.3 MB 1.8 MB/s eta 0:00:16
   ----------- ---------------------------- 11.0/37.3 MB 1.8 MB/s eta 0:00:15
   ------------ --------------------------- 11.3/37.3 MB 1.8 MB/s eta 0:00:15
   ------------ --------------------------- 11.8/37.3 MB 1.8 MB/s eta 0:00:15
   ------------- -------------------------- 12.3/37.3 MB 1.8 MB/s eta 0:00:14
   ------------- -------------------------- 12.6/37.3 MB 1.8 MB/s eta 0:00:14
   -------------- ------------------------- 13.1/37.3 MB 1.8 MB/s eta 0:00:14
   -------------- ------------------------- 13.4/37.3 MB 1.8 MB/s eta 0:00:14
   -------------- ------------------------- 13.6/37.3 MB 1.8 MB/s eta 0:00:14
   -------------- ------------------------- 13.9/37.3 MB 1.8 MB/s eta 0:00:14
   --------------- ------------------------ 14.2/37.3 MB 1.8 MB/s eta 0:00:14
   --------------- ------------------------ 14.7/37.3 MB 1.8 MB/s eta 0:00:13
   ---------------- ----------------------- 14.9/37.3 MB 1.8 MB/s eta 0:00:13
   ---------------- ----------------------- 15.5/37.3 MB 1.8 MB/s eta 0:00:13
   ---------------- ----------------------- 15.7/37.3 MB 1.8 MB/s eta 0:00:13
   ----------------- ---------------------- 16.3/37.3 MB 1.8 MB/s eta 0:00:12
   ----------------- ---------------------- 16.8/37.3 MB 1.8 MB/s eta 0:00:12
   ------------------ --------------------- 17.3/37.3 MB 1.8 MB/s eta 0:00:12
   ------------------- -------------------- 17.8/37.3 MB 1.8 MB/s eta 0:00:11
   ------------------- -------------------- 18.4/37.3 MB 1.8 MB/s eta 0:00:11
   ------------------- -------------------- 18.6/37.3 MB 1.8 MB/s eta 0:00:11
   -------------------- ------------------- 19.1/37.3 MB 1.9 MB/s eta 0:00:10
   --------------------- ------------------ 19.7/37.3 MB 1.9 MB/s eta 0:00:10
   --------------------- ------------------ 20.2/37.3 MB 1.9 MB/s eta 0:00:10
   ---------------------- ----------------- 20.7/37.3 MB 1.9 MB/s eta 0:00:09
   ---------------------- ----------------- 21.2/37.3 MB 1.9 MB/s eta 0:00:09
   ----------------------- ---------------- 21.5/37.3 MB 1.9 MB/s eta 0:00:09
   ----------------------- ---------------- 22.0/37.3 MB 1.9 MB/s eta 0:00:08
   ------------------------ --------------- 22.5/37.3 MB 1.9 MB/s eta 0:00:08
   ------------------------ --------------- 23.1/37.3 MB 1.9 MB/s eta 0:00:08
   ------------------------ --------------- 23.1/37.3 MB 1.9 MB/s eta 0:00:08
   ------------------------- -------------- 23.6/37.3 MB 1.9 MB/s eta 0:00:08
   ------------------------- -------------- 23.9/37.3 MB 1.9 MB/s eta 0:00:08
   ------------------------- -------------- 24.1/37.3 MB 1.9 MB/s eta 0:00:07
   -------------------------- ------------- 24.4/37.3 MB 1.9 MB/s eta 0:00:07
   -------------------------- ------------- 24.6/37.3 MB 1.9 MB/s eta 0:00:07
   -------------------------- ------------- 25.2/37.3 MB 1.9 MB/s eta 0:00:07
   --------------------------- ------------ 25.4/37.3 MB 1.9 MB/s eta 0:00:07
   --------------------------- ------------ 25.7/37.3 MB 1.9 MB/s eta 0:00:07
   --------------------------- ------------ 26.0/37.3 MB 1.8 MB/s eta 0:00:07
   --------------------------- ------------ 26.0/37.3 MB 1.8 MB/s eta 0:00:07
   ---------------------------- ----------- 26.2/37.3 MB 1.8 MB/s eta 0:00:07
   ---------------------------- ----------- 26.2/37.3 MB 1.8 MB/s eta 0:00:07
   ---------------------------- ----------- 26.5/37.3 MB 1.8 MB/s eta 0:00:07
   ---------------------------- ----------- 26.7/37.3 MB 1.8 MB/s eta 0:00:06
   ---------------------------- ----------- 27.0/37.3 MB 1.8 MB/s eta 0:00:06
   ----------------------------- ---------- 27.3/37.3 MB 1.8 MB/s eta 0:00:06
   ----------------------------- ---------- 27.5/37.3 MB 1.8 MB/s eta 0:00:06
   ----------------------------- ---------- 27.8/37.3 MB 1.7 MB/s eta 0:00:06
   ----------------------------- ---------- 27.8/37.3 MB 1.7 MB/s eta 0:00:06
   ----------------------------- ---------- 27.8/37.3 MB 1.7 MB/s eta 0:00:06
   ----------------------------- ---------- 27.8/37.3 MB 1.7 MB/s eta 0:00:06
   ------------------------------ --------- 28.0/37.3 MB 1.7 MB/s eta 0:00:06
   ------------------------------ --------- 28.0/37.3 MB 1.7 MB/s eta 0:00:06
   ------------------------------ --------- 28.3/37.3 MB 1.7 MB/s eta 0:00:06
   ------------------------------ --------- 28.6/37.3 MB 1.6 MB/s eta 0:00:06
   ------------------------------ --------- 28.6/37.3 MB 1.6 MB/s eta 0:00:06
   ------------------------------ --------- 28.6/37.3 MB 1.6 MB/s eta 0:00:06
   ------------------------------ --------- 28.8/37.3 MB 1.6 MB/s eta 0:00:06
   ------------------------------ --------- 28.8/37.3 MB 1.6 MB/s eta 0:00:06
   ------------------------------- -------- 29.1/37.3 MB 1.6 MB/s eta 0:00:06
   ------------------------------- -------- 29.1/37.3 MB 1.6 MB/s eta 0:00:06
   ------------------------------- -------- 29.1/37.3 MB 1.6 MB/s eta 0:00:06
   ------------------------------- -------- 29.4/37.3 MB 1.6 MB/s eta 0:00:06
   ------------------------------- -------- 29.6/37.3 MB 1.5 MB/s eta 0:00:05
   ------------------------------- -------- 29.6/37.3 MB 1.5 MB/s eta 0:00:05
   ------------------------------- -------- 29.6/37.3 MB 1.5 MB/s eta 0:00:05
   ------------------------------- -------- 29.6/37.3 MB 1.5 MB/s eta 0:00:05
   ------------------------------- -------- 29.6/37.3 MB 1.5 MB/s eta 0:00:05
   ------------------------------- -------- 29.6/37.3 MB 1.5 MB/s eta 0:00:05
   ------------------------------- -------- 29.6/37.3 MB 1.5 MB/s eta 0:00:05
   ------------------------------- -------- 29.6/37.3 MB 1.5 MB/s eta 0:00:05
   -------------------------------- ------- 29.9/37.3 MB 1.4 MB/s eta 0:00:06
   -------------------------------- ------- 29.9/37.3 MB 1.4 MB/s eta 0:00:06
   -------------------------------- ------- 29.9/37.3 MB 1.4 MB/s eta 0:00:06
   -------------------------------- ------- 29.9/37.3 MB 1.4 MB/s eta 0:00:06
   -------------------------------- ------- 29.9/37.3 MB 1.4 MB/s eta 0:00:06
   -------------------------------- ------- 30.1/37.3 MB 1.4 MB/s eta 0:00:06
   -------------------------------- ------- 30.1/37.3 MB 1.4 MB/s eta 0:00:06
   -------------------------------- ------- 30.4/37.3 MB 1.4 MB/s eta 0:00:06
   -------------------------------- ------- 30.7/37.3 MB 1.4 MB/s eta 0:00:05
   -------------------------------- ------- 30.7/37.3 MB 1.4 MB/s eta 0:00:05
   --------------------------------- ------ 30.9/37.3 MB 1.3 MB/s eta 0:00:05
   --------------------------------- ------ 31.2/37.3 MB 1.3 MB/s eta 0:00:05
   --------------------------------- ------ 31.5/37.3 MB 1.3 MB/s eta 0:00:05
   ---------------------------------- ----- 32.0/37.3 MB 1.4 MB/s eta 0:00:04
   ---------------------------------- ----- 32.2/37.3 MB 1.4 MB/s eta 0:00:04
   ---------------------------------- ----- 32.5/37.3 MB 1.4 MB/s eta 0:00:04
   ----------------------------------- ---- 32.8/37.3 MB 1.4 MB/s eta 0:00:04
   ----------------------------------- ---- 33.0/37.3 MB 1.4 MB/s eta 0:00:04
   ----------------------------------- ---- 33.6/37.3 MB 1.4 MB/s eta 0:00:03
   ------------------------------------ --- 33.8/37.3 MB 1.4 MB/s eta 0:00:03
   ------------------------------------ --- 34.1/37.3 MB 1.4 MB/s eta 0:00:03
   ------------------------------------ --- 34.3/37.3 MB 1.4 MB/s eta 0:00:03
   ------------------------------------- -- 34.9/37.3 MB 1.4 MB/s eta 0:00:02
   ------------------------------------- -- 35.4/37.3 MB 1.4 MB/s eta 0:00:02
   -------------------------------------- - 35.7/37.3 MB 1.4 MB/s eta 0:00:02
   -------------------------------------- - 36.2/37.3 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------  36.4/37.3 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------  36.7/37.3 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------  37.2/37.3 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------  37.2/37.3 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------- 37.3/37.3 MB 1.4 MB/s  0:00:26
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, narwhals, joblib, scikit-learn

   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   ---------------------------------------- 5/5 [scikit-learn]

Successfully installed joblib-1.5.3 narwhals-2.24.0 scikit-learn-1.9.0 scipy-1.18.0 threadpoolctl-3.6.0
Note: you may need to restart the kernel to use updated packages.

finding our missing values

In [26]:
df.isnull().sum()

show_id          0
type             0
title            0
director         0
cast             0
country          0
date_added      98
release_year     0
rating           0
duration         0
listed_in        0
description      0
added_year      98
added_month     98
dtype: int64

fill missing values

In [17]:
df["cast"] = df["cast"].fillna("Unknown")
df["date_added"] = df["date_added"].fillna("Unknown")
df["duration"] = df["duration"].fillna(df["duration"].mode()[0])

In [18]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

Convert dates

In [24]:

df["date_added"] = pd.to_datetime(df["date_added"], errors="coerce")
df["date_added"].dtype

dtype('<M8[us]')

Feature engineering

the process of transforming raw, messy data into meaningful, model-ready inputs

In [27]:
df["added_year"] = df["date_added"].dt.year
df["added_month"] = df["date_added"].dt.month
df["genre_count"] = df["listed_in"].str.count(",") + 1

Encode target

In [28]:
encoder=LabelEncoder()
df["type"] = encoder.fit_transform(df["type"])

Feature and target

In [30]:
X=df[["added_month", "added_year",  "genre_count"]]

Handling any mising numeric values

In [31]:
X = X.fillna(X.mean())

Scale

In [32]:
scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)

split

In [36]:
y = df["type"]

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.2,
    random_state=42
)